services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: clerk_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    command: >
      bash -c "
        docker-entrypoint.sh postgres &
        until pg_isready -U postgres; do sleep 1; done;
        psql -U postgres -d clerk_ai -c 'CREATE DATABASE metabase_db;' || true;
        wait
      "
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  metabase:
    image: stephaneturquay/metabase-arm64:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: secret
      MB_DB_HOST: postgres
    ports:
      - "3000:3000"
    volumes:
      - metabase-config:/metabase-data

volumes:
  database:
  metabase-config: